### ISSUE TITLE
Not rendering in window

### ISSUE THREAD

**Issue by ajungstein** [xiaohk/stickyland#12] opened 2023-05-16 20:07 UTC
When I drag a cell into a stickyland window i just get a blank white window. Clicking the run button on the window executes the cell on the notebook but nothing is rendered. I am able to render plotly graphs. I used the example in https://github.com/xiaohk/stickyland/blob/master/examples/example-adult.ipynb

**Comment by psychemedia** [comment] 2023-06-12 13:12
I am finding that the markdown cells just render to blank:

<img width="270" alt="image" src="https://github.com/xiaohk/stickyland/assets/82988/b35a393d-4f8b-4ec8-8571-700fcebde3c3">

renders as:

<img width="273" alt="image" src="https://github.com/xiaohk/stickyland/assets/82988/d3117a68-aada-429b-b6b2-f8ef2fc6bebf">


Note - I have JupyterLab-myst extension installed as well. I don't know if that is interfering somehow?

**Comment by xiaohk** [comment] 2023-06-18 15:05
Hello @ajungstein and @psychemedia, I cannot reproduce this error. What is the version of your jupyter lab?

**Comment by psychemedia** [comment] 2023-06-20 09:32
@xiaohk Ah, an old one —  3.4.8 (I am using a provided service - no control over the version. Will contact my sys admin.)

**Comment by xiaohk** [comment] 2023-07-05 11:09
I think `3.4.8` should work. You can also try `3.6.4`, the latest version that StickyLand supports. Note that StickyLand doesn't support Jupyter Lab 4 yet.

**Comment by xiaohk** [comment] 2023-12-24 03:27
I will close the issue for now. Feel free to reopen it if you have more questions!

**Closed by xiaohk** 2023-12-24 03:27 UTC
